### ISSUE TITLE
is it this plugin updated?

### ISSUE THREAD

**Issue by Kikobeats** [cedricziel/dokku-deployment-keys#23]
After install it and create ssh key under dokku `0.10.5`, I checked `$DOKKU_ROOT/.deployment-keys/shared/.ssh` and it doesn't exist.

Also doing `echo $DOKKU_ROOT` is doesn't return nothing :(

**Comment by josegonzalez** [comment]
`DOKKU_ROOT` isn't a magic global environment variable, but rather exists during a dokku run. It is equivalent to `/home/dokku`, so check that directory.

**Comment by Kikobeats** [comment]
Yes, I see, but the point is this plugin depends of `$DOKKU_ROOT` not just in the installation process, also when you want to perform any plugin action.

I had to add `$DOKKU_ROOT` inside my envs for get this plugin working as expected.

Maybe could be nice add default value?

**Comment by josegonzalez** [comment]
Where exactly are you seeing that it is "required" for any plugin action?

**Comment by Kikobeats** [comment]
For example, under `create` command: https://github.com/cedricziel/dokku-deployment-keys/blob/master/commands#L46

**Comment by josegonzalez** [comment]
Yeah, the `$DOKKU_ROOT` env var is set by dokku itself during regular runs. Are you somehow executing that script directly? Or are you using `dokku deploymentkeys:create` to do so?

**Comment by Kikobeats** [comment]
always directly with `dokku deploymentkeys:create`; Also when I revisited the folder to see the changes nothing sis here

**Comment by josegonzalez** [comment]
Strange, can you run that command like so:

```
dokku --trace deploymentkeys:create
```

And gist the output for us?

**Comment by Kikobeats** [comment]
of course! https://gist.github.com/Kikobeats/6bf5319e23cd8c4b4cf4b23776774629

**Comment by josegonzalez** [comment]
Specify an app name, but also $DOKKU_ROOT seems set.

**Comment by Kikobeats** [comment]
I removed the `$DOKKU_ROOT` declaration inside `environment` before, so yes, you're right. I going to adress the issue if I found another problem related with this.

Thanks for your time 😄
