### ISSUE TITLE
not compatible with dokku 0.12.11

### ISSUE THREAD

**Issue by sstutz** [cedricziel/dokku-deployment-keys#24]
I just setup a Server with Ubuntu 16.04 and installed dokku (not much configuration was done other than that)

Running
```bash
$ dokku plugin:install https://github.com/cedricziel/dokku-deployment-keys.git deployment-keys
```
did not result in echo'ing the generated key (as mentioned in #23 and #17), as a matter of fact it didn't even create one, I had to manually run ``` $ bash /var/lib/dokku/plugins/enabled/deployment-keys/install``` 

Running next
```bash
$ dokku deploymentkeys:create my-app
```
Does indeed return a key, saying "They will be baked into the container on next push/rebuild".

Browsing through the source code it looks like this plugin should create an /app/.ssh folder where it stores the keys after rebuilding it.

So on the host I did
 ``` $ dokku ps:rebuild my-app ```  

and on the client
 ```git push dokku master ``` 

neither build an image with this folder.

**Comment by josegonzalez** [comment]
This plugin only works for the herokuish builder, so ensure you're not building a dockerfile-based app when using it.
