### ISSUE TITLE
Does this plugin suppose to work with the latest dokku and Dockerfile deployment type?

### ISSUE THREAD

**Issue by ypadlyak** [cedricziel/dokku-deployment-keys#27]
I need it to fetch private ruby gem in Dockerfile commad

**Comment by josegonzalez** [comment]
It only supports buildpacks. You should specify a `--build-arg` option and pass in the ssh key that way for Dockerfile deployments.

**Comment by ypadlyak** [comment]
Thanks Jose!
Actually, I have figured out to pass ssh-agent by enabling BuildKit first. Works perfectly!
