### ISSUE TITLE
Key not available during composer build

### ISSUE THREAD

**Issue by sebastiaandegeus** [cedricziel/dokku-deployment-keys#4]
I added a key to the app and in github I added the result of `dokku deploymentkeys:show my_app_name` as a deployment key.

But still during the deployment when composer should be cloning the repo it crashes:

```
emote:
remote:
remote:   [RuntimeException]
remote:   Failed to execute git clone --no-checkout 'git@github.com:hoppinger/advanced-custom-fields-wpcli.git' 'web/app/plugins/advanced-custom-fields-wpcli/' && cd 'web/app/plugins/advanced-custom-fields-wpcli/' && git remote add composer 'git@github.com:hoppinger/advanced-custom-fields-wpcli.git' && git fetch composer
remote:
remote:

```

The repo is public. 

What am I missing here?

**Comment by cedricziel** [comment]
When the repo is public, you dont need a deployment key. What you are most probably searching for is my hostkeys plugin.

If the repos will remain public, you should clone it via https, not ssh. SSH requires a hostkey verification which you may or may not have done inside the container before.

**Comment by sebastiaandegeus** [comment]
We use a variety of public and private repos for this project inside the composer file.

It would be the cleanest if we can use ssh for both public and private repos.  

I will try the hostkeys plugin to see if I can get it working.

**Comment by sebastiaandegeus** [comment]
I got it working using both plugins. deployment-keys with adding the deploy key to the github private repo and hostkeys for the checkout of git repos in general to add github.com to the known_hosts

**Comment by cedricziel** [comment]
Good to hear; thx for reporting!
